import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import StoreProvider from "@/providers/StoreProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { ToastContainer } from "react-toastify";
import NuqsProvider from "@/providers/NuqsProvider";
import NextAuthProvider from "@/providers/NextAuthProvider";
import Navbar from "@/components/Navbar";
// Hapus import Footer dari react-day-picker
import Footer from "@/components/Footer"; // Gunakan Footer custom Anda

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <NuqsProvider>
            <StoreProvider>
              <ReactQueryProvider>
                <Navbar />
                {children}
                <Footer />
              </ReactQueryProvider>
              <ToastContainer />
            </StoreProvider>
          </NuqsProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}